-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 19:03:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academico` DEFAULT CHARACTER SET utf8 ;
USE `academico` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `Nome` VARCHAR(70) NOT NULL,
  `Descricao` VARCHAR(60) NOT NULL,
  `Diretor` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idDepartamento`),
  UNIQUE INDEX `idDepartamento_UNIQUE` (`idDepartamento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Curso` (
  `idCurso` INT NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Coordenador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`),
  UNIQUE INDEX `idCurso_UNIQUE` (`idCurso` ASC),
  INDEX `fk_Curso_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  CONSTRAINT `fk_Curso_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `academico`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Carga_Horaria` INT NOT NULL,
  `Ementa` VARCHAR(45) NOT NULL,
  `Bibliografia` VARCHAR(45) NOT NULL,
  `Pré-Requisitos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  UNIQUE INDEX `idDisciplina_UNIQUE` (`idDisciplina` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Aluno` (
  `idAluno` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Telefones` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAluno`),
  INDEX `fk_Aluno_Curso1_idx` (`Curso_idCurso` ASC),
  UNIQUE INDEX `idAluno_UNIQUE` (`idAluno` ASC),
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `academico`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Professor` (
  `idProfessor` INT NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Telefones` VARCHAR(45) NOT NULL,
  `Titulacao` VARCHAR(45) NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfessor`),
  INDEX `fk_Professor_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  UNIQUE INDEX `idProfessor_UNIQUE` (`idProfessor` ASC),
  CONSTRAINT `fk_Professor_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `academico`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Contato` (
  `idContato` INT NOT NULL,
  `Telefone` VARCHAR(17) NOT NULL,
  `Fax` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Homepage` VARCHAR(45) NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idContato`),
  INDEX `fk_Contato_Departamento_idx` (`Departamento_idDepartamento` ASC),
  UNIQUE INDEX `idContato_UNIQUE` (`idContato` ASC),
  CONSTRAINT `fk_Contato_Departamento`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `academico`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Turma` (
  `idTurma` INT NOT NULL,
  `Ano/Semestre` VARCHAR(45) NOT NULL,
  `Dias_Semana` VARCHAR(45) NOT NULL,
  `Horarios` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTurma`),
  UNIQUE INDEX `idTurma_UNIQUE` (`idTurma` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Sala` (
  `idSala` INT NOT NULL,
  `Numero` INT NOT NULL,
  `Bloco` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Capacidade` INT NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSala`),
  UNIQUE INDEX `idSala_UNIQUE` (`idSala` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Aula` (
  `idAula` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAula`),
  UNIQUE INDEX `idAula_UNIQUE` (`idAula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Calendario` (
  `idCalendario` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Semestre` INT NOT NULL,
  `Data_inicio` DATE NOT NULL,
  `Data_fim` DATE NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCalendario`),
  UNIQUE INDEX `idCalendario_UNIQUE` (`idCalendario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Data` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `fk_Avaliacao_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  UNIQUE INDEX `idAvaliacao_UNIQUE` (`idAvaliacao` ASC),
  CONSTRAINT `fk_Avaliacao_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `academico`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Historico` (
  `Aluno_idAluno` INT NOT NULL,
  `Data_Inscricao` DATE NOT NULL,
  `Data_inicio` DATE NOT NULL,
  `Data_Termino` DATE NOT NULL,
  `Tipo_Diploma` VARCHAR(45) NOT NULL,
  INDEX `fk_Historico_Aluno1_idx` (`Aluno_idAluno` ASC),
  CONSTRAINT `fk_Historico_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `academico`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma_na_Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Turma_na_Sala` (
  `Turma_idTurma` INT NOT NULL,
  `Sala_idSala` INT NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Sala_idSala`),
  INDEX `fk_Turma_has_Sala_Sala1_idx` (`Sala_idSala` ASC),
  INDEX `fk_Turma_has_Sala_Turma1_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Turma_has_Sala_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `mydb`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Sala_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `academico`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aula_na_Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Aula_na_Sala` (
  `Sala_idSala` INT NOT NULL,
  `Aula_idAula` INT NOT NULL,
  PRIMARY KEY (`Sala_idSala`, `Aula_idAula`),
  INDEX `fk_Sala_has_Aula_Aula1_idx` (`Aula_idAula` ASC),
  INDEX `fk_Sala_has_Aula_Sala1_idx` (`Sala_idSala` ASC),
  CONSTRAINT `fk_Sala_has_Aula_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `academico`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sala_has_Aula_Aula1`
    FOREIGN KEY (`Aula_idAula`)
    REFERENCES `academico`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Frequencia` (
  `Aluno_idAluno` INT NOT NULL,
  `Aula_idAula` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Presente` TINYINT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Aula_idAula`),
  INDEX `fk_Aluno_has_Aula_Aula1_idx` (`Aula_idAula` ASC),
  INDEX `fk_Aluno_has_Aula_Aluno1_idx` (`Aluno_idAluno` ASC),
  CONSTRAINT `fk_Aluno_has_Aula_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `academico`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Aula_Aula1`
    FOREIGN KEY (`Aula_idAula`)
    REFERENCES `academico`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Nota` (
  `Aluno_idAluno` INT NOT NULL,
  `Avaliacao_idAvaliacao` INT NOT NULL,
  `Valor` FLOAT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Avaliacao_idAvaliacao`),
  INDEX `fk_Aluno_has_Avaliacao_Avaliacao1_idx` (`Avaliacao_idAvaliacao` ASC),
  INDEX `fk_Aluno_has_Avaliacao_Aluno1_idx` (`Aluno_idAluno` ASC),
  CONSTRAINT `fk_Aluno_has_Avaliacao_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `academico`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Avaliacao_Avaliacao1`
    FOREIGN KEY (`Avaliacao_idAvaliacao`)
    REFERENCES `academico`.`Avaliacao` (`idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_na_Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Aluno_na_Turma` (
  `Aluno_idAluno` INT NOT NULL,
  `Turma_idTurma` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Turma_idTurma`),
  INDEX `fk_Aluno_has_Turma_Turma1_idx` (`Turma_idTurma` ASC),
  INDEX `fk_Aluno_has_Turma_Aluno1_idx` (`Aluno_idAluno` ASC),
  CONSTRAINT `fk_Aluno_has_Turma_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `academico`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Turma_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `academico`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Secretaria` (
  `idSecretaria` INT NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  `Nome` VARCHAR(70) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Data_Nascimento` DATE NULL,
  PRIMARY KEY (`idSecretaria`),
  INDEX `fk_Secretaria_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  CONSTRAINT `fk_Secretaria_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `academico`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academico`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `Nome` VARCHAR(70) NOT NULL,
  `Data_Nascimento` VARCHAR(45) NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `E-mail` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
